spring:
  application.name: client-management-service
  profiles.active: dev
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:clientsdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8091
  servlet.context-path: /

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl.defaultZone: http://localhost:8001/eureka/

logging:
  level:
    za.co.investec: DEBUG
    za.co.investec.assessment.clientmanagement.presentation.api.validation: OFF
    com.netflix: OFF
  file:
    name: client-management-service.log

springdoc:
  packages-to-scan: za.co.investec
  api-docs:
    path: /v1/api/docs
  swagger-ui:
    path: /api/swagger-ui.html